# VK: https://vk.com/sokolovskiyoleg
# DS: kent1997

rules:
  - '&c&lПравила сервера:'
  - '&bПравило первое: Не делайте то.'
  - '&eПравило второе: Соблюдайте это.'
  - '&dПравило третье: Уважайте других игроков.'
  - 'Правило четвёртое: Любить кентика'
  - 'Введите /rules accept, чтобы принять правила'
messages:
  non-player: '&cТолько игрок может использовать эту команду!'
  rules-accepted: '&aВы успешно подтвердили прочтение правил!'
  save-error: '&cПроизошла ошибка при сохранении файла! https://vk.com/sokolovskiyoleg'
  usage: '&cИспользование: /rules или /rules accept'
  confirm-rules: '&cПодтвердите прочтение правил!'
